# Generated by Django 3.2 on 2021-04-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='marca')),
            ],
            options={
                'verbose_name_plural': '1. Marcas ',
            },
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Tipo de producto ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('stock', models.BooleanField(default=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_1', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media')),
                ('imagen_2', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media')),
                ('imagen_3', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media')),
                ('imagen_4', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media')),
                ('imagen_5', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=999)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.marcas')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.tipo_producto')),
            ],
            options={
                'verbose_name_plural': '3. Producto ',
            },
        ),
    ]
