# Generated by Django 3.2 on 2021-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen_6',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media'),
        ),
    ]
