# Generated by Django 3.2 on 2021-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_product_imagen_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amarillo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='azul',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='bateria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='blanco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cafe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='carga_maxima',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='celeste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gris',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='negro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rojo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tiempo_carga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='turquesa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='velocidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='verde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='violeta',
            field=models.BooleanField(default=False),
        ),
    ]
