# Generated by Django 3.2 on 2021-04-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_auto_20210429_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagen_1',
            new_name='imagen_10_violeta',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagen_2',
            new_name='imagen_11_cafe',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagen_3',
            new_name='imagen_1_blanco',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagen_4',
            new_name='imagen_2_gris',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagen_5',
            new_name='imagen_3_negro',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagen_6',
            new_name='imagen_4_rojo',
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_5_amarillo',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_6_azul',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_7_celeste',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_8_verde',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_9_turquesa',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='media'),
        ),
    ]
