# Generated by Django 3.2 on 2021-04-30 03:25

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_auto_20210429_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amarillo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='azul',
        ),
        migrations.RemoveField(
            model_name='product',
            name='blanco',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='celeste',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gris',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_10_violeta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_11_cafe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_1_blanco',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_2_gris',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_3_negro',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_4_rojo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_5_amarillo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_6_azul',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_7_celeste',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_8_verde',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagen_9_turquesa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='negro',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rojo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='turquesa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='verde',
        ),
        migrations.RemoveField(
            model_name='product',
            name='violeta',
        ),
        migrations.CreateModel(
            name='Imagen_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='producto')),
                ('color', colorfield.fields.ColorField(default='#ffff', max_length=18)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.product')),
            ],
        ),
    ]
