# Generated by Django 3.2 on 2021-05-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_auto_20210429_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_producto',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
