# Generated by Django 3.2.4 on 2021-06-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_promo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
