# Generated by Django 3.2.4 on 2021-06-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0009_delete_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='controlador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensiones_rueda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='distancia_ejes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='frenos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
