# Generated by Django 3.2.4 on 2021-06-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0010_auto_20210617_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen_product',
            options={'verbose_name_plural': '4. Imagenes de Producto '},
        ),
    ]
