# Generated by Django 3.2.4 on 2021-06-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0011_alter_imagen_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.product')),
            ],
            options={
                'verbose_name_plural': '4. Galerìa de Producto ',
            },
        ),
    ]
