# Generated by Django 3.2.4 on 2021-06-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0012_galeria_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria_product',
            options={'verbose_name_plural': '5. Galerìa de Producto '},
        ),
    ]
