# Generated by Django 3.2 on 2021-04-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_electroruedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True)),
                ('celular_1', models.CharField(blank=True, max_length=11, null=True)),
                ('celular_2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Contacto ElecctroRuedas',
            },
        ),
        migrations.CreateModel(
            name='Contacto_redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '7. Contácto Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Electroruedas_galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_1', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media')),
                ('imagen_2', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media')),
                ('imagen_3', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media')),
                ('imagen_4', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media')),
                ('imagen_5', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '3. Inicio',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('nosotros', models.TextField(blank=True, max_length=500, null=True)),
                ('mision', models.TextField(blank=True, max_length=500, null=True)),
                ('vision', models.TextField(blank=True, max_length=500, null=True)),
                ('valor_1', models.TextField(blank=True, max_length=500, null=True)),
                ('valor_2', models.TextField(blank=True, max_length=500, null=True)),
                ('valor_3', models.TextField(blank=True, max_length=500, null=True)),
                ('valor_4', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Empresa',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '2. Slider',
            },
        ),
        migrations.AlterModelOptions(
            name='electroruedas',
            options={'verbose_name_plural': '1. Electroruedas'},
        ),
        migrations.RenameField(
            model_name='electroruedas',
            old_name='favicon_amarillo',
            new_name='favicon_blanco',
        ),
        migrations.RenameField(
            model_name='electroruedas',
            old_name='favicon_negro',
            new_name='favicon_color',
        ),
        migrations.RenameField(
            model_name='electroruedas',
            old_name='logo_amarillo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='electroruedas',
            old_name='logo_negro',
            new_name='logo_blanco',
        ),
        migrations.AddField(
            model_name='electroruedas',
            name='logo_horizontal_blanco',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
    ]
