# Generated by Django 3.2 on 2021-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_auto_20210429_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sub_titulo_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sub_titulo_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
