# Generated by Django 3.2 on 2021-04-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_auto_20210429_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Beneficios',
            },
        ),
    ]
