# Generated by Django 3.2 on 2021-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='detalle_valor_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='detalle_valor_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='detalle_valor_3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='detalle_valor_4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
