# Generated by Django 3.2 on 2021-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_auto_20210429_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Valor',
            },
        ),
        migrations.AlterModelOptions(
            name='beneficios',
            options={'verbose_name_plural': '6. Beneficios'},
        ),
        migrations.AlterModelOptions(
            name='contacto_electroruedas',
            options={'verbose_name_plural': '7. Contacto ElecctroRuedas'},
        ),
        migrations.AlterModelOptions(
            name='contacto_redes',
            options={'verbose_name_plural': '8. Contácto Redes Sociales'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='detalle_valor_1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='detalle_valor_2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='detalle_valor_3',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='detalle_valor_4',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='valor_1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='valor_2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='valor_3',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='valor_4',
        ),
    ]
