# Generated by Django 3.2 on 2021-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_auto_20210429_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sub_titulo_3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='detalle',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
