# Generated by Django 3.2 on 2021-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_auto_20210429_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sub_titulo_4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo_4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
