# Generated by Django 3.2 on 2021-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0009_auto_20210429_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imagen_6',
            field=models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media'),
        ),
    ]
