# Generated by Django 3.2 on 2021-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0011_auto_20210429_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='articulo')),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Valor',
            },
        ),
    ]
