# Generated by Django 3.2 on 2021-05-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0013_auto_20210505_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_diario',
            name='link',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='articulo_diario',
            name='parrafo_1',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='articulo_diario',
            name='parrafo_2',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
