# Generated by Django 3.2 on 2021-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0014_auto_20210505_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Electroruedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon_color', models.ImageField(help_text='imagenes 20*20', upload_to='favicon')),
                ('logo_horizontal', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon')),
            ],
            options={
                'verbose_name_plural': '1. Electroruedas',
            },
        ),
        migrations.DeleteModel(
            name='Electroruedas',
        ),
    ]
