# Generated by Django 3.2 on 2021-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0015_auto_20210505_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imagen_7',
            field=models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imagen_8',
            field=models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media'),
        ),
    ]
