# Generated by Django 3.2 on 2021-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0016_auto_20210505_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imagen_9',
            field=models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media'),
        ),
    ]
