# Generated by Django 3.2 on 2021-06-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0017_electroruedas_galeria_imagen_9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='mision',
            new_name='quienes_somos',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='vision',
        ),
    ]
