# Generated by Django 3.2 on 2021-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0018_auto_20210604_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficioss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Beneficios',
            },
        ),
        migrations.RenameModel(
            old_name='Beneficios',
            new_name='Ventajas',
        ),
        migrations.AlterModelOptions(
            name='ventajas',
            options={'verbose_name_plural': '6. Ventajas'},
        ),
    ]
