# Generated by Django 3.2 on 2021-06-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0019_auto_20210604_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficioss',
            new_name='Beneficios',
        ),
    ]
