# Generated by Django 3.2 on 2021-06-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0023_auto_20210604_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_1',
        ),
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imag_empresa',
            field=models.ImageField(blank=True, help_text='Empresa - Seccion Quienes somos imagenes 300*500', null=True, upload_to='electroruedas'),
        ),
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imag_fondo_ventajas',
            field=models.ImageField(blank=True, help_text='Inicio - Seccion Ventajas imagenes 300*900', null=True, upload_to='electroruedas'),
        ),
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imag_ventaja_01',
            field=models.ImageField(blank=True, help_text='Empresa - Seccion Quienes somos imagenes 300*500', null=True, upload_to='electroruedas'),
        ),
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imag_ventaja_02',
            field=models.ImageField(blank=True, help_text='Empresa - Seccion Quienes somos imagenes 300*500', null=True, upload_to='electroruedas'),
        ),
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imag_ventaja_03',
            field=models.ImageField(blank=True, help_text='Empresa - Seccion Quienes somos imagenes 300*500', null=True, upload_to='electroruedas'),
        ),
    ]
