# Generated by Django 3.2 on 2021-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0024_auto_20210607_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electroruedas_galeria',
            name='imag_ventaja_01',
            field=models.ImageField(blank=True, help_text='Empresa - Seccion Ventaja 300*500', null=True, upload_to='electroruedas'),
        ),
        migrations.AlterField(
            model_name='electroruedas_galeria',
            name='imag_ventaja_02',
            field=models.ImageField(blank=True, help_text='Empresa - Seccion Ventaja 300*500', null=True, upload_to='electroruedas'),
        ),
        migrations.AlterField(
            model_name='electroruedas_galeria',
            name='imag_ventaja_03',
            field=models.ImageField(blank=True, help_text='Empresa - Seccion Ventaja 300*500', null=True, upload_to='electroruedas'),
        ),
    ]
