# Generated by Django 3.2.4 on 2021-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0025_auto_20210607_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_smtp', models.CharField(max_length=100)),
                ('puerto', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('copia', models.EmailField(max_length=200)),
                ('mensaje_personalizado', models.TextField(default='Gracias por elegir xurimotos')),
            ],
        ),
    ]
