# Generated by Django 3.2.4 on 2021-06-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0027_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
