# Generated by Django 3.2.4 on 2021-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0028_promo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
