# Generated by Django 3.2.4 on 2021-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0029_promo_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imag_ventaja_03',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_2',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_3',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_4',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_5',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_6',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_7',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_8',
        ),
        migrations.RemoveField(
            model_name='electroruedas_galeria',
            name='imagen_9',
        ),
        migrations.AddField(
            model_name='electroruedas_galeria',
            name='imagen_distribuidor',
            field=models.ImageField(blank=True, help_text='Quieres ser distribuidor -  500*500', null=True, upload_to='media'),
        ),
    ]
