# Generated by Django 3.2.4 on 2021-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0031_alter_electroruedas_galeria_imagen_distribuidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_electroruedas',
            name='logo_horizontal_2',
            field=models.ImageField(blank=True, help_text='Logotipo un color 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='electroruedas_galeria',
            name='imagen_distribuidor',
            field=models.ImageField(blank=True, help_text='Quieres ser distribuidor -  500*900', null=True, upload_to='electroruedas'),
        ),
        migrations.AlterField(
            model_name='marca_electroruedas',
            name='favicon_color',
            field=models.ImageField(help_text='Favicon 20*20', upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='marca_electroruedas',
            name='logo_horizontal',
            field=models.ImageField(blank=True, help_text='Logotipo a color 50*200', null=True, upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Inicio - Sección Slider 500*900', null=True, upload_to='media'),
        ),
    ]
